server:
 port: 8080

ureka:
 client:
  fetch-registry: true
  register-with-eureka: true
  service-url:
   default-zone: http://localhost:8761/eureka
  instance:
   hostname: localhost

spring:
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true
  routes:
   - id: Usuario-Servicio
     uri: lb://Usuario-Servicio
     predicates:
      - Path=/user/**    
   - id: Carro-Servicio
     uri: lb://Carro-Servicio
     predicates:
      - Path=/carro/**   
   - id: Moto-Servicio
     uri: lb://Moto-Servicio
     predicates:
      - Path=/moto/**   